/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>

#include <smlib>
#include <morecolors>

//
#define SPECMODE_NONE 				0
#define SPECMODE_FIRSTPERSON 		4
#define SPECMODE_3RDPERSON 			5
#define SPECMODE_FREELOOK	 		6

//
Handle healthTimer[MAXPLAYERS+1];


//Hud
Handle hMessage;

public Plugin:myinfo = 
{
	name = "NMRiH Game Tools",
	author = "Cee",
	description = "Color chat, health display, status display, death message for NMRiH",
	version = "1.0",
	url = "http://www.srgaming.net"
};

public OnPluginStart()
{
	hMessage = CreateHudSynchronizer();
	
	//玩家死亡
	HookEvent("player_death", Events_OnPlayerDeath);
	
	AddCommandListener(Command_Say, "say");
	
	RegConsoleCmd("sm_ammo", Command_Ammo);
	
	for(new i = 1; i < MaxClients; i ++)
	{
		if(IsClientInGame(i))
			OnClientPutInServer(i);
	}
}

public OnMapEnd()
{
	for(new i = 1; i < MaxClients; i ++)
	{
		if(IsClientInGame(i))
		{
			if(healthTimer[i] != null)
			{
				healthTimer[i].Close();
				healthTimer[i] = null;
			}
		}
	}
}

public OnClientPutInServer(client)
{
	if(healthTimer[client] != null)
		healthTimer[client].Close();
		
	healthTimer[client] = CreateTimer(0.5, Timer_DisplayHealth, client, TIMER_FLAG_NO_MAPCHANGE|TIMER_REPEAT);
}

public OnClientDisconnected(client)
{
	if(healthTimer[client] != null)
	{
		healthTimer[client].Close();
		healthTimer[client] = null;
	}
}

public Action:Command_Ammo(client, args)
{
	for(new i = 1; i < 124; i ++)
	{
		PrintToConsole(client, "i: %d || ammo: %d", i, GetEntData(client, i, 1));
	}
}

public Action:Events_OnPlayerDeath(Event event, const String:name[], bool:dontBroadcast)
{
	CPrintToChatAll("{blue}[死亡提示] {white}弱者 {red}%N {white}为何要战斗?!", GetClientOfUserId(GetEventInt(event, "userid")));
}

public OnClientConnected(client)
{
	CPrintToChatAll("{white}玩家{yellow} %N {white}连接服务器...", client);
}

public OnClientDisconnect(client)
{
	CPrintToChatAll("{white}玩家{yellow} %N {white}退出服务器", client);
}

public Action:Command_Say(client, const String:cmd[], args)
{
	decl String:sArg[255];
	GetCmdArgString(sArg, sizeof(sArg));
	StripQuotes(sArg);
	
	CPrintToChatAll("%s{blue}%N {white}:  %s", !IsPlayerAlive(client) ? "(死亡) {orange}*{white}" : "", client, sArg);
	
	return Plugin_Handled;
}

public Action:Timer_DisplayHealth(Handle:timer, any:client)
{
	DisplayStatusToClient(client);
	return Plugin_Continue;
}

stock DisplayStatusToClient(client)
{
	if(!IsClientInGame(client))
		return;
		
	new target = client;
	
	//玩家死亡时显示观察对象的数据
	if(!IsPlayerAlive(client))
	{
		new iObserverMode = GetEntProp(client, Prop_Send, "m_iObserverMode");
		if(iObserverMode == SPECMODE_FIRSTPERSON || iObserverMode == SPECMODE_3RDPERSON)
			target = GetEntPropEnt(client, Prop_Send, "m_hObserverTarget");
	}
		
	
	//血量
	decl String:sHealth[255];
	if(IsPlayerAlive(target))
		FormatEx(sHealth, 255, "%d", GetClientHealth(target));
	else
		Format(sHealth, 255, "死亡");
		
	//武器
	decl String:sWeapon[128];
	new iAmmo, weapon = GetEntPropEnt(target, Prop_Data, "m_hActiveWeapon");
	if(IsValidEntity(weapon))
	{
		GetEntityClassname(weapon, sWeapon, sizeof(sWeapon));
		iAmmo = GetEntProp(weapon, Prop_Send, "m_iClip1");
	}
	else
		Format(sWeapon, sizeof(sWeapon), "无武器");
		
	decl String:sAmmo[8];
	if(iAmmo == 255)
		FormatEx(sAmmo, sizeof(sAmmo), "无");
	else
		FormatEx(sAmmo, sizeof(sAmmo), "%d", iAmmo);
	
	//耐力
	new Float:Stamina = GetEntPropFloat(target, Prop_Send, "m_flStamina");
	
	//负重
	new iWeight = GetEntProp(target, Prop_Send, "_carriedWeight", 1);
	
	//状态信息
	decl String:Buffer[255];
	Format(Buffer, sizeof(Buffer), "血量: %s | 武器: %s | 体力: %.02f^x25 | 负重: %.1f^x25 | 子弹: %s \n状态: ", sHealth, sWeapon, (Stamina/130.0)*100.0, (float(iWeight)/1000.0)*100.0, sAmmo);
	
	if(client != target)
		Format(Buffer, sizeof(Buffer), "玩家: %N | %s", target, Buffer);
	
	decl String:sStatus[128] = "";
	if(GetEntProp(target, Prop_Send, "m_bDiedWhileInfected") == 1)
		Format(sStatus, sizeof(sStatus), "%s|感染死亡", sStatus);
	
	if(GetEntProp(target, Prop_Send, "m_bIsSprinting") == 1)
		Format(sStatus, sizeof(sStatus), "%s|奔跑", sStatus);
		
	if(GetEntProp(target, Prop_Send, "m_bPoisoned") == 1)
		Format(sStatus, sizeof(sStatus), "%s|中毒", sStatus);
	
	if(GetEntProp(target, Prop_Send, "_bleedingOut") == 1)
		Format(sStatus, sizeof(sStatus), "%s|出血", sStatus);
	
	if(GetEntProp(target, Prop_Send, "_vaccinated") == 1)
		Format(sStatus, sizeof(sStatus), "%s|免疫", sStatus);
		
	if(GetEntProp(target, Prop_Send, "m_bGrabbed") == 1)
		Format(sStatus, sizeof(sStatus), "%s|被控", sStatus);
		
	if(GetEntPropFloat(target, Prop_Send, "m_flInfectionTime") > 0.0)
		Format(sStatus, sizeof(sStatus), "%s|感染", sStatus);
		
	if(strlen(sStatus) == 0)
		Format(Buffer, sizeof(Buffer), "%s正常", Buffer);
	else
	{
		if(sStatus[0] == '|')
			Format(Buffer, sizeof(Buffer), "%s%s", Buffer, sStatus[1]);
		else
			Format(Buffer, sizeof(Buffer), "%s%s", Buffer, sStatus);
	}
	
	//显示消息
	DisplayStatusMessage(client, Buffer);
}

stock DisplayStatusMessage(client, String:fmt[], any:...)
{
	new String:buffer[255];
	VFormat(buffer, sizeof(buffer), fmt, 3);
	
	//Replace ^x25 to %
	ReplaceString(buffer, sizeof(buffer), "^x25", "%%");
	
	SetHudTextParams(0.02, 0.82, 2.0, 255, 0, 0, 0);
	ShowSyncHudText(client, hMessage, buffer);
}